# Generated by Django 4.1.2 on 2023-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abt_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
