# Generated by Django 4.1.2 on 2023-01-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_about_abt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abt_title',
            field=models.CharField(max_length=200),
        ),
    ]
